### ISSUE TITLE
Define Test Strategy for API

### ISSUE THREAD

**Issue by FellipeGiulianoDuarte** [bet-blocker/bet-blocker-api#14]
# Issue: Define Test Strategy for API  

## Description  
To ensure the **quality** and **reliability** of the project's API, we need a structured test strategy. This includes selecting tools for manual and automated API testing, defining the test scope, and setting up workflows to validate the API's functionality, performance, and error handling.  

I propose using **Postman** or **Insomnia** as the primary tool for API testing. These tools offer user-friendly interfaces, robust testing capabilities, and seamless collaboration features.  

---

## Suggested Strategy  

1. **Tool Selection**  
   - Use **Postman** for its extensive collaboration and automation capabilities, or **Insomnia** for a streamlined testing experience.  
   - Both tools support creating collections, running automated tests, and visualizing responses.  

2. **Test Scope**  
   - **Functional Tests**: Verify endpoints are working as expected.  
   - **Negative Tests**: Ensure the API handles invalid inputs gracefully.  
   - **Performance Tests**: Check response times and rate limits.  
   - **Edge Case Tests**: Handle large payloads, unexpected data types, or unusual inputs.  

3. **Test Automation**  
   - Use Postman Collections or Insomnia Scripts to automate recurring test scenarios.  
   - Integrate test runs into the CI/CD pipeline for continuous validation.  

4. **Documentation**  
   - Document API test cases, including preconditions, steps, and expected outcomes.  
   - Share testing collections and configurations with the team to ensure consistency.  

---

## Tasks  

- Select the preferred tool.
- Set up API test collections covering:  
  - Authentication  
  - CRUD operations for endpoints  
  - Error handling scenarios  
- Automate critical test cases for efficiency.  
- Document test workflows and share with the team.  

---

## Questions  

- Are there specific endpoints or features that need immediate testing?  
- Does the team already use one of these tools, or is there a preference?  
- Should we prioritize integration with CI/CD for automated test execution?

**Comment by brunohash** [comment]
Hello, Felipe.

We are putting a lot of effort into reaching a high level of security and conducting the necessary tests. Any help is welcome! We are already discussing various testing strategies, such as unit tests, performance tests, functionality tests, among others.

Feel free to support us with this: https://shibarmy.postman.co/workspace/626e4972-59da-4690-9831-10befa4a26cb/overview
