### ISSUE TITLE
[FEAT] Criar paginação para melhorar a performance do response

### ISSUE THREAD

**Issue by jhowbhz** [bet-blocker/bet-blocker-api#4]
Sugestão para melhorar a velocidade do response é adicionar uma paginação no retorno, o que acham?

**Comment by RobsonTrasel** [comment]
Uma boa mesmo, tem meu apoio.

**Comment by RobsonTrasel** [comment]
Essa **issue** atualmente está dependente da **issue** #7 pois do jeito que estamos fazendo atualmente seria muito trabalhoso e creio eu que teríamos coisas mais prioritárias no momento.

**Comment by brunohash** [comment]
A new version of the tool has been released, speeding up the process by 95%. You can check this in our Readme. We’ll discuss performance further soon, but for now, I believe we are on the right track.
