### ISSUE TITLE
[BUG] Não está retornando corretamente o dns reverso do dominio

### ISSUE THREAD

**Issue by jhowbhz** [bet-blocker/bet-blocker-api#5]
Repare que no callback está errado o retorno do dns reverso

```   "DNS": {
        "Type": "InterNetwork",
        "Name": "a5sbet.com",
        "Host": "a5sbet.com",
        "ReverseDns": "104.21.42.168",
        "CanonicalName": "a5sbet.com",
        "TTl": "3600",
        "ResolvedAt": "2024-11-09T17:48:37.149205Z"
      },
      "Protocols": {
        "Https": true,
        "Http": true
      },
      "Ips": {
        "Ip": "104.21.42.168",
        "ResolvedAt": "2024-11-09T17:48:37.149204Z"
      },```

**Comment by brunohash** [comment]
Precisamos fazer um pente fino nesse objeto!

**Comment by PabloVenino** [comment]
Subi um PR agora, para sanar esse bug.
Só precisa daquela revisada :)

**Comment by brunohash** [comment]
@PabloVenino, obrigado pela contribuição! Ainda sim, precisamos revisar essa DTO pois tem alguns erros na montagem do objeto.

**Comment by PabloVenino** [comment]
> @PabloVenino, obrigado pela contribuição! Ainda sim, precisamos revisar essa DTO pois tem alguns erros na montagem do objeto.

Ai seria melhor quando finalizar o Banco, que vi que estão implementando, o que acha?

**Comment by RobsonTrasel** [comment]
> > @PabloVenino, obrigado pela contribuição! Ainda sim, precisamos revisar essa DTO pois tem alguns erros na montagem do objeto.
> 
> Ai seria melhor quando finalizar o Banco, que vi que estão implementando, o que acha?

Essa sua mudança já está em vigor pra melhor uso, depois temos que dar uma refactor dentro desses DTO

**Comment by PabloVenino** [comment]
Sim!! Isso mesmo que quis dizer!
Vou acompanhando as issues e vendo com o que posso contribuir :)

**Comment by RobsonTrasel** [comment]
Show, fechando essa issue porque ja foi resolvida.
