### ISSUE TITLE
[FEAT] Block List em banco de dados

### ISSUE THREAD

**Issue by brunohash** [bet-blocker/bet-blocker-api#7]
Sugestão de pararmos de lidar com hosts via arquivo json e começar a lidar com ele via banco de dados.. atualmente temos 0 controle sobre hosts repetidos e também perdemos o poder das queries.

**Comment by RobsonTrasel** [comment]
Opa, beleza, sugere qual banco de dados para isso ? Eu penso em um Postgres da vida.

**Comment by brunohash** [comment]
Gosto da performance do MongoDb, como não precisamos fazer joins complexos podíamos partir daí.

**Comment by RobsonTrasel** [comment]
Comecei essa implementação, usando o Atlas do Mongo.

**Comment by RobsonTrasel** [comment]
Eu fiz os commits nessa issue #6, era para ter ido para essa issue aqui hahah, o importante é que vai estar lá.

**Comment by RobsonTrasel** [comment]
Fechando a issue aqui, porem, @brunohash preciso que de uma olhada pra mim nessa ultima action que tentei fazer para subir as alterações, a primeira tentativa foi quase 5min o processo de deploy.
